package client.view;

import client.controller.ClientCtr;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import shared.dto.ObjectWrapper;
import shared.dto.PlayerHistory;

public class RankingFrm extends javax.swing.JFrame {

    private ClientCtr clientCtr;

    public RankingFrm(ClientCtr clientController) {
        clientCtr = clientController;
        initComponents();
        setLocationRelativeTo(null);
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            System.out.println("In result form: ");
            clientCtr.sendData(new ObjectWrapper(ObjectWrapper.GET_RANKING));
        }
        super.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblRanking = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Quay về trang chủ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblRanking.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRanking.setText("BẢNG XẾP HẠNG");

        lblPlayer.setText("name player");

        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Username", "Số trận thắng", "Số trận thua", "Số trận AFK", "Tổng điểm", "Rank"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRanking);
        if (tblRanking.getColumnModel().getColumnCount() > 0) {
            tblRanking.getColumnModel().getColumn(0).setResizable(false);
            tblRanking.getColumnModel().getColumn(1).setResizable(false);
            tblRanking.getColumnModel().getColumn(2).setResizable(false);
            tblRanking.getColumnModel().getColumn(3).setResizable(false);
            tblRanking.getColumnModel().getColumn(4).setResizable(false);
            tblRanking.getColumnModel().getColumn(5).setResizable(false);
            tblRanking.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addGap(17, 17, 17)
                .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        clientCtr.getMainFrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JTable tblRanking;
    // End of variables declaration//GEN-END:variables

    public void receivedDataProcessing(ObjectWrapper data) {
        switch (data.getPerformative()) {
            case ObjectWrapper.SERVER_SEND_RANKING:
                List<PlayerHistory> leaderboard = (List<PlayerHistory>) data.getData();

                String[] columnNames = {"STT", "Username", "Số trận thắng", "Số trận thua", "Số trận AFK", "Tổng điểm", "Rank"};
                DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

                int index = 1; // Số thứ tự bắt đầu từ 1
                for (PlayerHistory player : leaderboard) {
                    Object[] rowData = {
                        index++,
                        player.getUsername(),
                        player.getTotalWins(),
                        player.getTotalLosses(),
                        player.getTotalAfk(),
                        player.getPoints(),
                        player.getRanking()
                    };
                    tableModel.addRow(rowData);
                }

                tblRanking.setModel(tableModel);
                break;
        }
    }
}
