package client.view;

import client.controller.ClientCtr;
import shared.dto.ObjectWrapper;

public class ResultFrm extends javax.swing.JFrame {

    private ClientCtr mySocket;

    public ResultFrm(ClientCtr clientCtr) {
        mySocket = clientCtr;
        initComponents();
        setLocationRelativeTo(null);
        lblResultDetail.setVisible(false);
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            System.out.println("In result form: ");
            mySocket.sendData(new ObjectWrapper(ObjectWrapper.GET_RESULT));
        }
        super.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNamePlayer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPlayerPoint = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNameEnemy = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEnemyPoint = new javax.swing.JLabel();
        lblResultDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Quay về trang chủ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblResult.setText("BẠN ĐÃ CHIẾN THẮNG");

        lblPlayer.setText("name player");

        jLabel1.setText("Bạn:");

        lblNamePlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamePlayer.setText("namePlayer");

        jLabel2.setText("Thay đổi điểm:");

        lblPlayerPoint.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPlayerPoint.setText("+1");

        jLabel3.setText("Đối thủ:");

        lblNameEnemy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNameEnemy.setText("nameEnemy");

        jLabel4.setText("Thay đổi điểm:");

        lblEnemyPoint.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnemyPoint.setText("Không đổi");

        lblResultDetail.setText("h");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNameEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(lblPlayerPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEnemyPoint))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblResultDetail)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNamePlayer)
                    .addComponent(jLabel2)
                    .addComponent(lblPlayerPoint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNameEnemy)
                    .addComponent(jLabel4)
                    .addComponent(lblEnemyPoint))
                .addGap(95, 95, 95)
                .addComponent(btnBack)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mySocket.sendData(new ObjectWrapper(ObjectWrapper.BACK_TO_MAIN_FORM));

        mySocket.getMainFrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEnemyPoint;
    private javax.swing.JLabel lblNameEnemy;
    private javax.swing.JLabel lblNamePlayer;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerPoint;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResultDetail;
    // End of variables declaration//GEN-END:variables

    public void receivedDataProcessing(ObjectWrapper data) {
        switch (data.getPerformative()) {
            case ObjectWrapper.SERVER_SEND_RESULT:
                String[] resultAndUserNameEnemy = ((String) data.getData()).split("\\|\\|");

                String result = resultAndUserNameEnemy[0];
                String usernameEnemy = resultAndUserNameEnemy[1];

                lblPlayer.setText(mySocket.getUsername());
                lblNamePlayer.setText(mySocket.getUsername());
                lblNameEnemy.setText(usernameEnemy);

                if (result.equals("win")) {
                    lblResult.setText("BẠN ĐÃ CHIẾN THẮNG");
                    lblPlayerPoint.setText("+1");
                    lblEnemyPoint.setText("Không đổi");
                } else if (result.equals("loss")) {
                    lblResult.setText("BẠN ĐÃ THUA CUỘC");
                    lblEnemyPoint.setText("+1");
                    lblPlayerPoint.setText("Không đổi");
                } else if (result.equals("cancelled")) {
                    lblResult.setText("TRẬN ĐẤU KẾT THÚC");
                    lblResultDetail.setVisible(true);
                    lblResultDetail.setText("Trận đấu kết thúc vì đối thủ của bạn đã rời đi");
                    lblEnemyPoint.setText("-1");
                    lblPlayerPoint.setText("Không đổi");
                } else if (result.equals("draw")) {
                    lblResult.setText("HOÀ");
                    lblResultDetail.setVisible(true);
                    lblResultDetail.setText("Trận đấu kết thúc vì cả 2 người chơi bỏ lượt liên tục 3 lần");
                    lblEnemyPoint.setText("Không đổi");
                    lblPlayerPoint.setText("Không đổi");
                }

                break;
        }
    }
}
